"""add song.photo

Revision ID: 22822fd1f521
Revises: 8865a6589615
Create Date: 2022-04-21 21:08:30.712015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22822fd1f521'
down_revision = '8865a6589615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('photo', sa.VARCHAR(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'photo')
    # ### end Alembic commands ###
